STAT 7900 – Python for Data Science<br>
Homework 5<br>
Connor Armstrong<br>
<br>
Due midnight Sunday, March 28<br>
<br>
1.	(14 pts) using einsum and the matricies below: <br>

In [7]:
import numpy as np
A = np.array((4,2,-3,3,-3,-5,1,-4,1,4)).reshape(5,2)
B = np.array((-5,0,1,5,0,1,1,-2,-1,-1)).reshape(5,2)
C = np.array((-3,-2,-1,5,2,1,-4,1,0,1,1,-3,0,2,-5)).reshape(5,3)

print("A")
print(A)
print()
print("B")
print(B)
print()
print("C")
print(C)

A
[[ 4  2]
 [-3  3]
 [-3 -5]
 [ 1 -4]
 [ 1  4]]

B
[[-5  0]
 [ 1  5]
 [ 0  1]
 [ 1 -2]
 [-1 -1]]

C
[[-3 -2 -1]
 [ 5  2  1]
 [-4  1  0]
 [ 1  1 -3]
 [ 0  2 -5]]


<br>	
1.a.  *Calculate the size of A* <br>

In [9]:
print(A.shape)

(5, 2)


<br>
1.b.	Calculate the simple position by position multiplication of A and B<br>


In [12]:
A*B

array([[-20,   0],
       [ -3,  15],
       [  0,  -5],
       [  1,   8],
       [ -1,  -4]])

<br>
1.c.	Calculate the inner product of A and B (to result in a scaler)<br>


In [13]:
np.einsum('ij, ij', A, B)

-9

<br>
1.d.	Calculate the inner product of A and B to result in a length 5 array<br>


In [14]:
np.einsum('ij, ij -> i', A, B)

array([-20,  12,  -5,   9,  -5])

<br>
1.e.	Calculate the matrix multiplication of A and C to result in a 3 x 2 matrix<br>


In [19]:
np.einsum('ij, ik -> kj', A, C)

array([[-14,  25],
       [-14,   1],
       [-15,  -7]])

<br>
1.f.	How does this differ from creating a resulting 3 x 2 matrix that is the inner product along the row dimension and the outer product of the column dimensions?<br>


In [21]:
np.einsum('ij, ik', A, C)#inner product of A and C

array([[-14, -14, -15],
       [ 25,   1,  -7]])

The resulting matrices from 1.e and 1.f are the transpose of one another.<br>
<br>

<br>
1.g.	Calculate the full outer product of A and C resulting in a 5 x 2 x 3 matrix<br>

In [22]:
np.einsum('ij, ik -> ijk', A, C)

array([[[-12,  -8,  -4],
        [ -6,  -4,  -2]],

       [[-15,  -6,  -3],
        [ 15,   6,   3]],

       [[ 12,  -3,   0],
        [ 20,  -5,   0]],

       [[  1,   1,  -3],
        [ -4,  -4,  12]],

       [[  0,   2,  -5],
        [  0,   8, -20]]])

<br>
2.	(26 pts) Find the web page that contains the information on the sci-kit learn multi-layer perceptron classifier library: <br><br>
I think this is it<br>
https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html



<br>
2.a.	In which larger library is this library found (not “sklearn”, but the sub-library between the classifier and the overall sklearn library). <br><br>
sklearn.neural_network


<br>
2.b.	What are the default settings for:<br><br>

&emsp;&emsp;i.	 learning rate<br>
&emsp;&emsp;&emsp;&emsp;0.001<br><br>

&emsp;&emsp;ii.	Batch size<br>
&emsp;&emsp;&emsp;&emsp;batch_size=min(200, n_samples)<br><br>

&emsp;&emsp;iii.	Hidden layer size<br>
&emsp;&emsp;&emsp;&emsp;100<br><br>

&emsp;&emsp;iv.	Solver<br>
&emsp;&emsp;&emsp;&emsp;adam, which refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy Ba<br><br>

&emsp;&emsp;v.	Activation function<br>
&emsp;&emsp;&emsp;&emsp;relu, the rectified linear unit function, returns f(x) = max(0, x)<br>


<br>
2.c.	(4 pts) What is the implication of the default random state, in terms of the ability for someone else to exactly reproduce your work?<br><br>
With no default random state, and without specifying a seed, the algorithm will use a random state which is unlikely to be replicated, as it will likely derive the random state from the system clock.


<br>
2.d.	In your own words (do not copy and paste from the site or you’ll get 0 credit), explain the following methods and when/how would you use them: <br><br>

&emsp;&emsp;i.	fit<br>
&emsp;&emsp;&emsp;&emsp;This method takes an input matrix with dimensions (number of observations by number of variables) and an array with dimensions (number of observations by number of outputs) and returns a trained Multi-Layer Perceptron (MLP) Model. As a method, fit(X, y) is used as a modifier to the MLPClassifier function of interest. For example, the method is used in the example code in the following context:<br><br>
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)<br><br>

&emsp;&emsp;ii.	get_parms<br>
&emsp;&emsp;&emsp;&emsp;This method is used to specify whether to output parameter estimates for the specified estimator(s) using a TRUE/FALSE input.<br><br>

&emsp;&emsp;iii.	predict<br>
&emsp;&emsp;&emsp;&emsp;This method requires an input matrix of dimensions (number of samples by number of variables) and returns the predicted classes. This is useful for model evaluation purposes as you can input a test array and compare it the predicted output to the true output.<br><br>

&emsp;&emsp;iv.	predict_proba<br>
&emsp;&emsp;&emsp;&emsp;similar to predict but returns a probability instead of a prediction.<br><br>

&emsp;&emsp;v.	score<br>
&emsp;&emsp;&emsp;&emsp;Takes test data, target array, and sample weights as input and returns a mean score as output. This is a harsh scoring since it requires all attributes to be predicted successfully to be given credit toward the score. This is useful for model optimization and evaluation.<br><br>